# https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/configuring-dependabot-version-updates
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      gomod-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
