version: "2"

run:
  timeout: 60m
  go: "1.25"
  modules-download-mode: vendor

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - errcheck
    - gocritic
    - govet
    - ineffassign
    #- nakedret
    - misspell
    #- nolintlint
    #- nlreturn
    - reassign
    - staticcheck
    - unused
    - unconvert
    - unparam
    # - wastedassign # disabled because of generics
    # - whitespace # Disabled for performance reasons - Ignores cache and takes 12+ minutes to run on the repo for _any_ change
  settings:
    misspell:
      ignore-words:
        - hdinsight
        - exportfs
    nakedret:
      max-func-lines: 40
  exclusions:
    paths:
      - /sdk/ # Excluding sdk folders as these are externally generated

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - /sdk/ # Excluding sdk folders as these are externally generated
