terraform {
  required_providers {
    azapi = {
      source = "Azure/azapi"
    }
  }
}

provider "azapi" {
  skip_provider_registration = false
}

variable "resource_name" {
  type    = string
  default = "acctest0001"
}

variable "location" {
  type    = string
  default = "eastus"
}

resource "azapi_resource" "resourceGroup" {
  type     = "Microsoft.Resources/resourceGroups@2020-06-01"
  name     = var.resource_name
  location = var.location
}

resource "azapi_resource" "grafana" {
  type      = "Microsoft.Dashboard/grafana@2023-09-01"
  parent_id = azapi_resource.resourceGroup.id
  name      = "${var.resource_name}-graf"
  location  = var.location
  body = {
    properties = {
      apiKey                            = "Disabled"
      autoGeneratedDomainNameLabelScope = "TenantReuse"
      deterministicOutboundIP           = "Disabled"
      grafanaMajorVersion               = "11"
      publicNetworkAccess               = "Enabled"
      zoneRedundancy                    = "Disabled"
    }
    sku = {
      name = "Standard"
    }
  }
}

resource "azapi_resource" "account" {
  type      = "Microsoft.Monitor/accounts@2023-04-03"
  parent_id = azapi_resource.resourceGroup.id
  name      = "${var.resource_name}-mw"
  location  = var.location
  body = {
    properties = {
      publicNetworkAccess = "Enabled"
    }
  }
}

resource "azapi_resource" "managedPrivateEndpoint" {
  type      = "Microsoft.Dashboard/grafana/managedPrivateEndpoints@2023-09-01"
  parent_id = azapi_resource.grafana.id
  name      = "${var.resource_name}-mpe"
  location  = var.location
  body = {
    properties = {
      groupIds                  = ["prometheusMetrics"]
      privateLinkResourceId     = azapi_resource.account.id
      privateLinkResourceRegion = var.location
      privateLinkServiceUrl     = ""
      requestMessage            = ""
    }
  }
}

