---
name: Bicep Types Update

on:
  schedule:
    - cron: '0 18 * * 0'
  workflow_dispatch:
  push:
    branches:
      - workflow-testing/bicep-types-update

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_bicep_types_and_push_to_a_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout azure-rest-api-specs
        uses: actions/checkout@v4
        with:
          repository: Azure/azure-rest-api-specs
          path: azure-rest-api-specs
          fetch-depth: 1

      - name: Checkout bicep-types-az
        uses: actions/checkout@v4
        with:
          repository: Azure/bicep-types-az
          path: bicep-types-az
          fetch-depth: 1
          submodules: recursive

      - name: List folder structure of cloned repos
        run: |
          echo "Folder structure of azure-rest-api-specs:"
          ls -R azure-rest-api-specs
          echo "Folder structure of bicep-types-az:"
          ls -R bicep-types-az

      - name: Force push current state to update branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin HEAD:refs/heads/gh-action/bicep-types-update --force
          echo "PR creation link: ${{ github.server_url }}/${{ github.repository }}/compare/main...gh-action/bicep-types-update?expand=1"
