---
name: GoLang Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  golint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: 'v2.11.4'
          args: -v ./internal/... --timeout=10m
