---
name: Go Security Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  gosec:
     name: gosec
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Source
         uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

       - name: Run Gosec Security Scanner
         uses: securego/gosec@deb54465fea23d19a77f037e11e6589021f8501d # v2.29.0
         with:
           args: './...'
