---
name: Unit Tests
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.7'
      - run: chmod -R +x ./scripts
      - run: bash scripts/gogetcookie.sh
      - run: make test
        env:
          GITHUB_ACTIONS_STAGE: "UNIT_TESTS"
